### ISSUE TITLE
Dos branches

### ISSUE THREAD

**Issue by alu0101130026** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct11-async-sockets-alu0101130026#1]
Buenas tardes, he empezado mi proyecto en el branch main haciendo todo el tema de las actions, coveralls, sonarcloud... pero en vscode trabajando en el proyecto en sí. Una vez realizo el push solo me lo hace en un nuevo branch (master). Hay algún problema con que esto se quede así como está? Es decir, en una branch el proyecto con src, tests... y en la otra los workflows. @esegredo @amarrerod @alu0101130026

**Comment by esegredo** [comment]
Hola, buenas tardes.

No debería haber problema siempre y cuando los flujos de trabajo se ejecuten en la rama que quieres (porque así lo especificas en los ficheros que los definen). En cualquier caso, podrías hacer un `merge` de ambas ramas.

Saludos.
